# Generated by Django 4.2.7 on 2025-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('genero', models.CharField(choices=[('ficcion', 'Ficción'), ('no_ficcion', 'No Ficción'), ('misterio', 'Misterio'), ('romance', 'Romance'), ('ciencia_ficcion', 'Ciencia Ficción'), ('fantasia', 'Fantasía'), ('biografia', 'Biografía'), ('historia', 'Historia'), ('filosofia', 'Filosofía'), ('poesia', 'Poesía'), ('teatro', 'Teatro'), ('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('tecnologia', 'Tecnología'), ('autoayuda', 'Autoayuda'), ('otros', 'Otros')], max_length=50, verbose_name='Género')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
